
observation_sources: laser_scan_sensor #point_cloud_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

robot_radius: 0.200

transform_tolerance: 0.4
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 2.5
 raytrace_range: 3.5
 inflation_radius: 0.3
 track_unknown_space: false
 combination_method: 1

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.3   # max distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "map"
