# static_map - True if using existing map

global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
  # cost_factor = 0.55
  # neutral_cost = 66

  resolution: 0.5
  static_map: true
  # width: 10.0
  # height: 10.0

  transform_tolerance: 1.0
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

